language: php

php:
    - 5.5
    - 5.6
    - 7.0

install: composer install

before_script:
    - composer validate --strict
    - mysql -e 'CREATE DATABASE wp_cli_test;' -uroot
    - mysql -e 'GRANT ALL PRIVILEGES ON wp_cli_test.* TO "wp_cli_test"@"localhost" IDENTIFIED BY "password1"' -uroot

script: composer run-behat

cache:
  directories:
    - vendor

notifications:
    email:
        on_success: never
        on_failure: change
